language: node_js
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
script:
  - printf "API_URL=$API_URL\nAUTH=$AUTH" > .env.build
  - npm run dev &
  - npm test
  - npx wait-on tcp:3000
  - npm run test:e2e
